- hosts: [{{host}}]
  become: yes
  tasks:
    - dnf: name=docker state=present enablerepo=updates-testing
    - lineinfile:
        dest: /etc/sysconfig/docker-network
        regexp: "DOCKER_NETWORK_OPTIONS=.*"
        line: DOCKER_NETWORK_OPTIONS="--bridge={{iface}} --iptables=false --ip-masq=false"
    - service: name=docker.service enabled=yes state=restarted
