- hosts: [{{host}}]
  become: yes
  tasks:
    - package: name=bridge-utils state=present
    - template:
        src: {{templates_dir}}/ifcfg
        dest: /etc/sysconfig/network-scripts/ifcfg-{{name}}
    - service: name=network.service state=restarted
