- hosts: [{{host}}]
  become: yes
  tasks:
    - shell: ip addr show | grep {{ipaddr}} | awk '{print $NF}'
      register: enabled_iface
      ignore_errors: True
    - shell: ip li de {{'{{'}}enabled_iface.stdout{{'}}'}}
      when: enabled_iface.stdout != "{{name}}"
    - shell: rm -f /etc/sysconfig/network-scripts/ifcfg-{{'{{'}}enabled_iface.stdout{{'}}'}}
      when: ansible_distribution == "Fedora"
    - template:
        src: {{templates_dir}}/ifcfg
        dest: /etc/sysconfig/network-scripts/ifcfg-{{name}}
        when: ansible_distribution == "Fedora"
    - service: name=network.service state=restarted
      when: ansible_distribution == "Fedora"
    - shell: rm -f /etc/network/interfaces.d/{{'{{'}}enabled_iface.stdout{{'}}'}}.cfg
      when: ansible_distribution == "Ubuntu"
    - template:
        src: {{templates_dir}}/ifcfg
        dest: /etc/network/interfaces.d/{{name}}.cfg
        when: ansible_distribution == "Ubuntu"
    - service: name=networking.service state=restarted
      when: ansible_distribution == "Ubuntu"
