- hosts: [{{host}}]
  become: yes
  tasks:
    - get_url:
        url: http://storage.googleapis.com/kubernetes-release/release/{{k8s_version}}/bin/linux/amd64/kubelet
        dest: /usr/bin/kubelet
    - shell: chmod +x /usr/bin/kubelet
    - file: name=/etc/kubernetes/manifests state=directory
    - template:
        src: {{templates_dir}}/kubelet.service
        dest: /etc/systemd/system/kubelet.service
    - template:
        src: {{templates_dir}}/kube-proxy.manifest
        dest: /etc/kubernetes/manifests/kube-proxy.manifest
    - shell: systemctl daemon-reload
    - service: name=kubelet state=restarted enabled=yes
