handler: ansible
version: 1.0.0
input:
  etcd_authority:
    schema: str!
    value: null
  cni_netd:
    schema: str!
    value: /etc/cni/net.d
  log_level:
    schema: str!
    value: info
  version:
    schema: str!
    value: v1.2.0
