- hosts: [{{host}}]
  become: yes
  tasks:
    # without these lines: can't create /var/log/etcd.log: Is a directory
    - file: name=/var/log/etcd.log state=touch
    - file: name=/var/log/etcd-events.log state=touch

    - template:
        src: {{templates_dir}}/etcd.manifest
        dest: /etc/kubernetes/manifests/etcd.manifest
