handler: ansible
version: 1.0.0
input:
  ip:
    schema: str!
    value: null
  etcd_authority:
    schema: str!
    value: null
  kubernetes:
    schema: bool!
    value: false
  etcd_authority_internal:
    schema: str!
    value: null
    computable:
      lang: python
      type: full
      func: |
        return R[resource_name]['etcd_authority'].replace('http://', '')
