---
- name: Ensure pool range is correct for hardcoded kubedns definition
  assert:
    that:
      - "\"{{ kube_service_addresses }}\" == \"10.233.0.0/18\""
# FIXME(mattymo): Shift to templated pods or revert to using KPM
- name: Copy kubedns rc
  copy:
    src: kubedns-rc.yml
    dest: /etc/kubernetes/kubedns-rc.yml
    owner: root
    group: root
    mode: 0644
  register: kubedns_rc

- name: Copy kubedns svc
  copy:
    src: kubedns-svc.yml
    dest: /etc/kubernetes/kubedns-svc.yml
    owner: root
    group: root
    mode: 0644
  register: kubedns_svc

- name: Deploy kubedns rc
  command: "{{ bin_dir }}/kubectl replace --force -f /etc/kubernetes/kubedns-rc.yml"
  when: kubedns_rc.changed

- name: Deploy kubedns svc
  command: "{{ bin_dir }}/kubectl replace --force  -f /etc/kubernetes/kubedns-svc.yml"
  when: kubedns_svc.changed

- name: Wait for kubedns to be ready
  shell: "nslookup kubernetes.default.svc.{{ cluster_name }} {{ dns_server }}"
  register: kubernetes_resolvable
  until: kubernetes_resolvable.rc == 0
  delay: 5
  retries: 20

- name: Copy network test script
  copy:
    src: test_networking.sh
    dest: "{{ bin_dir }}/test_networking.sh"
    owner: root
    group: root
    mode: 0755

- name: Test networking connectivity
  shell: "bash {{ bin_dir }}/test_networking.sh"
  changed_when: false
  become: no

- name: Copy dashboard definition
  copy:
    src: kubernetes-dashboard.yml
    dest: /etc/kubernetes/kubernetes-dashboard.yml
    owner: root
    group: root
    mode: 0644
  register: dashboard

- name: Create Kubernetes dashboard
  command: "{{ bin_dir }}/kubectl create -f /etc/kubernetes/kubernetes-dashboard.yml"
  when: dashboard.changed
