- hosts: [{{host}}]
  become: yes
  tasks:
    - dnf: name=kubernetes state=present enablerepo=updates-testing
    - template:
        src: {{templates_dir}}/kubernetes_config
        dest: /etc/kubernetes/config
    - file: name=/var/run/kubernetes state=directory
    - shell: chown kube:kube /var/run/kubernetes
    - shell: chmod 750 /var/run/kubernetes
    - template:
        src: {{templates_dir}}/apiserver
        dest: /etc/kubernetes/apiserver
    {% for service in ["etcd", "kube-apiserver", "kube-controller-manager", "kube-scheduler"] %}
    - service: name={{service}} state=restarted enabled=yes
    {% endfor %}

