handler: ansible
version: 1.0.0
input:
  name:
    schema: str!
    value: cbr0
  netmask:
    schema: str!
    value: null
  prefix:
    schema: int!
    value: null
  type:
    schema: str!
    value: null
  ipaddr:
    schema: str!
    value: null
  onboot:
    schema: str!
    value: "yes"
  bootproto:
    schema: str!
    value: static
