- hosts: [{{host}}]
  become: yes
  tasks:
    - get_url:
        url: http://storage.googleapis.com/kubernetes-release/release/{{k8s_version}}/bin/linux/amd64/kubectl
        dest: /usr/bin/kubectl
    - get_url:
        url: http://storage.googleapis.com/kubernetes-release/release/{{k8s_version}}/bin/linux/amd64/kubelet
        dest: /usr/bin/kubelet
    - shell: chmod +x /usr/bin/kubectl
    - shell: chmod +x /usr/bin/kubelet
    - file: name=/etc/kubernetes/manifests state=directory
    - template:
        src: {{templates_dir}}/kubelet.service
        dest: /etc/systemd/system/kubelet.service
    - template:
        src: {{templates_dir}}/kubelet_master.manifest
        dest: /etc/kubernetes/manifests/kubelet_master.manifest
    - service: name=kubelet state=restarted enabled=yes
    - wait_for: host={{master_host}} port={{master_port}} connect_timeout=5 state=started timeout=60
    - shell: kubectl get namespaces
      register: kube_namespaces
    - shell: kubectl create namespace kube-system
      when: "'kube-system' not in kube_namespaces.stdout"
