- hosts: [{{host}}]
  become: yes
  tasks:
    - package: name=docker state=present enablerepo=updates-testing
    {% if network_options %}
    - lineinfile:
        dest: /etc/sysconfig/docker-network
        regexp: "DOCKER_NETWORK_OPTIONS=.*"
        line: DOCKER_NETWORK_OPTIONS="--bridge={{iface}} --iptables=false --ip-masq=false"
    {% endif %}
    - service: name=docker.service enabled=yes state=restarted
