handler: none
version: 1.0.0
input:
  cluster_dns:
    schema: str!
    value: null
  cluster_domain:
    schema: str!
    value: null
  netmask:
    schema: str!
    value: '255.255.255.0'
  prefix:
    schema: int!
    value: 16
  network:
    schema: str!
    value: '172.20.0.0'
  service_cluster_ip_range:
    schema: str!
    value: 10.254.0.0/16
