handler: ansible
version: 1.0.0

input:
  master_port:
    schema: int
    value: 8080
  master_host:
    schema: str
    value: null
  master_address:
    schema: str
    value: null
    computable:
      lang: jinja2
      type: full
      func: |
        http://{{master_host}}:{{master_port}}
  etcd_servers:
    schema: [str!]
    value: []
  api_bind_port:
    schema: int
    value: 8080
  api_bind_address:
    schema: str
    value: 0.0.0.0
  admission_control:
    schema: str!
    value: NamespaceLifecycle,NamespaceExists,LimitRanger,SecurityContextDeny,ResourceQuota
